<?php
if (!defined('_GNUBOARD_')) exit;

// 품목별 재화등에 관한 상품요약 정보
$item_info = array(
    "wear"=>array(
        "title"=>"의류",
        "productInfoProvidedNoticeType" => "WEAR",
        "article"=>array(
            "material"=>array("제품소재", "섬유의 조성 또는 혼용률을 백분율로 표시, 기능성인 경우 성적서 또는 허가서"),
            "color"=>array("색상", ""),
            "size"=>array("치수", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein" => array("제조국", ""),
            "caution"=>array("세탁방법 및 취급시 주의사항", ""),
            "manufacturing_ym"=>array("제조연월", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "shoes"=>array(
        "title"=>"구두/신발",
        "productInfoProvidedNoticeType" => "SHOES",
        "article"=>array(
            "material"=>array("제품 주소재", "운동화인 경우에는 겉감, 안감을 구분하여 표시"),
            "color"=>array("색상", ""),
            "size"=>array("치수-발길이", "해외사이즈 표기 시 국내사이즈 병행 표기 (mm)"),
            "height"=>array("치수-굽높이", "굽 재료를 사용하는 여성화에 한함 (cm)"),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "caution"=>array("취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "bag"=>array(
        "title"=>"가방",
        "productInfoProvidedNoticeType" => "BAG",
        "article"=>array(
            "kind"=>array("종류", ""),
            "material"=>array("소재", ""),
            "color"=>array("색상", ""),
            "size"=>array("크기", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "caution"=>array("취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "fashion"=>array(
        "title"=>"패션잡화(모자/벨트/액세서리)",
        "productInfoProvidedNoticeType" => "FASHION_ITEMS",
        "article"=>array(
            "kind"=>array("종류", ""),
            "material"=>array("소재", ""),
            "size"=>array("치수", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "caution"=>array("취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "bedding"=>array(
        "title"=>"침구류/커튼",
        "productInfoProvidedNoticeType" => "SLEEPING_GEAR",
        "article"=>array(
            "material"=>array("제품소재", "(섬유의 조성 또는 혼용률을 백분율로 표시) 충전재를 사용한 제품은 충전재를 함께 표기"),
            "color"=>array("색상", ""),
            "size"=>array("치수", ""),
            "component" =>array("제품구성", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "caution"=>array("세탁방법 및 취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "furniture"=>array(
        "title"=>"가구(침대/소파/싱크대/DIY제품)",
        "productInfoProvidedNoticeType" => "FURNITURE",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "certification"=>array("KC 인증 필 유무", "(전기용품및생활용품안전관리법상 공급자적합성확인대상에 한함)"),
            "color"=>array("색상", ""),
            "component"=>array("구성품", ""),
            "material"=>array("주요소재", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)<br />구성품 별 제조자가 다른 경우 각 구성품의 제조자, 수입자"),
            "madein"=>array("제조국", "구성품 별 제조국이 다른 경우 각 구성품의 제조국"),
            "size"=>array("크기", ""),
            "delivery"=>array("배송&middot;설치비용", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "image_appliances"=>array(
        "title"=>"영상가전 (TV류)",
        "productInfoProvidedNoticeType" => "IMAGE_APPLIANCES",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "certification"=>array("KC 인증 필 유무", "전기용품및생활용품안전관리법상 안전인증대상전기용품, 안전확인대상전기용품, 공급자적합성확인대상전기용품에 한함"),
            "rated_voltage"=>array("정격전압", ""),
            "power_consumption"=>array("소비전력", ""),
            "energy_efficiency"=>array("에너지소비효율등급", "에너지이용합리화법 상 의무대상상품에 한함"),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "size"=>array("크기", "형태포함"),
            "display_specification"=>array("화면사양", "크기, 해상도, 화면비율 등"),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "home_appliances"=>array(
        "title"=>"가정용전기제품(냉장고/세탁기/식기세척기/전자레인지)",
        "productInfoProvidedNoticeType" => "HOME_APPLIANCES",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "certification"=>array("KC 인증 필 유무", "전기용품및생활용품안전관리법상 안전인증대상전기용품, 안전확인대상전기용품, 공급자적합성확인대상전기용품에 한함"),
            "rated_voltage"=>array("정격전압", ""),
            "power_consumption"=>array("소비전력", ""),
            "energy_efficiency"=>array("에너지소비효율등급", "에너지이용합리화법 상 의무대상상품에 한함"),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "size"=>array("크기", "용량, 형태포함"),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "season_appliances"=>array(
        "title"=>"계절가전(에어컨/온풍기)",
        "productInfoProvidedNoticeType" => "SEASON_APPLIANCES",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "certification"=>array("KC 인증 필 유무", "전기용품및생활용품안전관리법상 안전인증대상전기용품, 안전확인대상전기용품, 공급자적합성확인대상전기용품에 한함"),
            "rated_voltage"=>array("정격전압", ""),
            "power_consumption"=>array("소비전력", ""),
            "energy_efficiency"=>array("에너지소비효율등급", "에너지이용합리화법 상 의무대상상품에 한함"),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "size"=>array("크기", "형태 및 실외기 포함"),
            "area"=>array("냉난방면적", ""),
            "installation_costs"=>array("추가설치비용", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "office_appliances"=>array(
        "title"=>"사무용기기(컴퓨터/노트북/프린터)",
        "productInfoProvidedNoticeType" => "OFFICE_APPLIANCES",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "certification"=>array("KC 인증 필 유무", "전파법 상 인증대상상품에 한함, MIC 인증 필 혼용 가능"),
            "rated_voltage"=>array("정격전압", ""),
            "power_consumption"=>array("소비전력", ""),
            "energy_efficiency"=>array("에너지효율등급", "에너지이용합리화법 상 의무대상상품에 한함"),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "size"=>array("크기", ""),
            "weight"=>array("무게", "무게는 노트북에 한함"),
            "specification"=>array("주요사양", "컴퓨터와 노트북의 경우 성능, 용량, 운영체제 포함여부 등 / 프린터의 경우 인쇄 속도 등"),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "optics_appliances"=>array(
        "title"=>"광학기기(디지털카메라/캠코더)",
        "productInfoProvidedNoticeType" => "OPTICS_APPLIANCES",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "certification"=>array("KC 인증 필 유무", "전파법 상 인증대상상품에 한함, MIC 인증 필 혼용 가능"),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "size"=>array("크기", ""),
            "weight"=>array("무게", ""),
            "specification"=>array("주요사양", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "microelectronics"=>array(
        "title"=>"소형전자(MP3/전자사전등)",
        "productInfoProvidedNoticeType" => "MICROELECTRONICS",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "certification"=>array("KC 인증 필 유무", "전파법 상 인증대상상품에 한함, MIC 인증 필 혼용 가능"),
            "rated_voltage"=>array("정격전압", ""),
            "power_consumption"=>array("소비전력", ""),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "size"=>array("크기", ""),
            "weight"=>array("무게", ""),
            "specification"=>array("주요사양", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "mobile"=>array(
        "title"=>"휴대폰",
        "productInfoProvidedNoticeType" => "CELLPHONE",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "certification"=>array("KC 인증 필 유무", "전파법 상 인증대상상품에 한함, MIC 인증 필 혼용 가능"),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "size"=>array("크기", ""),
            "weight"=>array("무게", ""),
            "telecom"=>array("이동통신사", ""),
            "join_process"=>array("가입절차", ""),
            "extra_burden"=>array("소비자의 추가적인 부담사항", "가입비, 유심카드 구입비 등 추가로 부담하여야 할 금액, 부가서비스, 의무사용기간, 위약금 등"),
            "specification"=>array("주요사양", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "navigation"=>array(
        "title"=>"네비게이션",
        "productInfoProvidedNoticeType" => "NAVIGATION",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "certification"=>array("KC 인증 필 유무", "전파법 상 인증대상상품에 한함, MIC 인증 필 혼용 가능"),
            "rated_voltage"=>array("정격전압", ""),
            "power_consumption"=>array("소비전력", ""),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "size"=>array("크기", ""),
            "weight"=>array("무게", ""),
            "specification"=>array("주요사양", ""),
            "update_cost"=>array("맵 업데이트 비용", ""),
            "freecost_period"=>array("무상기간", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "car"=>array(
        "title"=>"자동차용품(자동차부품/기타자동차용품)",
        "productInfoProvidedNoticeType" => "CAR_ARTICLES",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "released_date"=>array("동일모델의 출시년월", ""),
            "certification"=>array("KC 인증 필 유무", "자동차관리법에 따른 자기인증 대상 자동차부품에 한함"),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", "구성품 별 제조국이 다른 경우 각 구성품의 제조국"),
            "size"=>array("크기", ""),
            "apply_model"=>array("적용차종", ""),
            "caution"=>array("제품사용으로 인한 위험 및 유의사항", "연료절감장치에 한함"),
            "warranty"=>array("품질보증기준", ""),
            "pass_number"=>array("검사합격증 번호", "대기환경보전법에 따른 첨가제&middot;촉매제에 한함"),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "medical"=>array(
        "title"=>"의료기기",
        "productInfoProvidedNoticeType" => "MEDICAL_APPLIANCES",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "license_number"=>array("의료기기법상 허가&middot;신고 번호", "허가&middot;신고 대상 의료기기에 한함"),
            "advertising"=>array("광고사전심의필 유무", ""),
            "rated_voltage"=>array("정격전압", "전기용품에 한함"),
            "power_consumption"=>array("소비전력", "전기용품에 한함"),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "appliances_purpose"=>array("제품의 사용목적", ""),
            "appliances_usage"=>array("제품의 사용방법", ""),
            "caution"=>array("취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "kitchenware"=>array(
        "title"=>"주방용품",
        "productInfoProvidedNoticeType" => "KITCHEN_UTENSILS",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "material"=>array("재질", ""),
            "component"=>array("구성품", ""),
            "size"=>array("크기", ""),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "import_declaration"=>array("수입식품안전관리특별법에 따른 수입 신고", "수입식품안전관리특별법에 따른 수입 기구&middot;용기의 경우 \"수입식품안전관리특별법에 따른 수입신고를 필함\"의 문구"),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "cosmetics"=>array(
        "title"=>"화장품",
        "productInfoProvidedNoticeType" => "COSMETIC",
        "article"=>array(
            "capacity"=>array("용량 또는 중량", ""),
            "specification"=>array("제품 주요사양", "피부타입, 색상(호, 번) 등"),
            "expiration_date"=>array("사용기한 또는 개봉 후 사용기간", "개봉 후 사용기간을 기재할 경우에는 제조연월일을 병행표기"),
            "usage"=>array("사용방법", ""),
            "maker"=>array("화장품제조업자", ""),
            "distributor"=>array("화장품책임판매업자", ""),
            "madein"=>array("제조국", ""),
            "mainingredient"=>array("주요성분", "화장품법에 따라 기재&middot;표시하여야 하는 모든 성분 "),
            "certification"=>array("식품의약품안전청 심사 필 유무", "기능성 화장품의 경우 화장품법에 따른 식품의약품안전청 심사 필 유무 (미백, 주름개선, 자외선차단 등)"),
            "caution"=>array("사용할 때 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("소비자상담관련 전화번호", ""),
        )
    ),
    "jewelry"=>array(
        "title"=>"귀금속/보석/시계류",
        "productInfoProvidedNoticeType" => "JEWELLERY",
        "article"=>array(
            "material"=>array("소재", ""),
            "purity"=>array("순도", ""),
            "band"=>array("밴드재질", "시계의 경우"),
            "weight"=>array("중량", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", "원산지와 가공지 등이 다를 경우 함께 표기"),
            "size"=>array("치수", ""),
            "caution"=>array("착용 시 주의사항", ""),
            "specification"=>array("주요사양", "귀금속, 보석류는 등급, 시계는 기능, 방수 등"),
            "provide_warranty"=>array("보증서 제공여부", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "food"=>array(
        "title"=>"식품(농수축산물)",
        "productInfoProvidedNoticeType" => "FOOD",
        "article"=>array(
            "product_name"=>array("품목 또는 명칭", ""),
            "weight"=>array("포장단위별 용량(중량)", ""),
            "quantity"=>array("포장단위별 수량", ""),
            "size"=>array("포장단위별 크기", ""),
            "producer"=>array("생산자", "수입품의 경우 수입자를 함께 표기"),
            "origin"=>array("원산지", "농수산물의 원산지 표시에 관한 법률에 따른 원산지"),
            "manufacturing_ymd"=>array("제조연월일", "포장일 또는 생산연도"),
            "expiration_date"=>array("유통기한", ""),
            "law_content"=>array("관련법상 표시사항", "농산물 - 농산물품질관리법상 유전자변형농산물 표시, 지리적표시<br />축산물 - 축산법에 따른 등급 표시, 축산물이력법에 따른 이력관리대상축산물 유무<br />수산물 - 농수산물품질관리법상 유전자변형수산물 표시,지리적 표시<br />수입식품에 해당하는 경우  \"수입식품안전관리특별법에 따른 수입신고를 필함\"의 문구"),
            "product_composition"=>array("상품구성", ""),
            "keep"=>array("보관방법 또는 취급방법", ""),
            "caution"=>array("식품등의표시·광고에관한법률에 따른 소비자안전을 위한 주의사항", ""),
            "as"=>array("소비자상담 관련 전화번호", ""),
        )
    ),
    "general_food"=>array(
        "title"=>"가공식품",
        "productInfoProvidedNoticeType" => "GENERAL_FOOD",
        "article"=>array(
            "product_name"=>array("제품명", ""),
            "food_type"=>array("식품의 유형", ""),
            "producer"=>array("생산자", "수입품의 경우 생산자,수입자"),
            "location"=>array("소재지", "수입품의 경우 제조국"),
            "manufacturing_ymd"=>array("제조연월일", ""),
            "expiration_date"=>array("유통기한 또는 품질유지기한", ""),
            "weight"=>array("포장단위별 내용물의 용량(중량)", ""),
            "quantity"=>array("포장단위별 수량", ""),
            "ingredients"=>array("원재료명 및 함량", "농수산물의 원산지 표시에 관한 법률에 따른 원산지 표시 포함"),
            "nutrition_component"=>array("영양성분", "식품등의표시&middot;광고에관한법률에 따른 영양성분 표시대상 식품에 한함"),
            "genetically_modified"=>array("유전자변형식품에 해당하는 경우의 표시", ""),
            "caution"=>array("소비자안전을 위한 주의사항", ""),
            "imported_food"=>array("수입식품에 해당하는 경우 “수입식품안전관리특별법에 따른 수입신고를 필함”의 문구", ""),
            "as"=>array("소비자상담 관련 전화번호", ""),
        )
    ),
    "diet_food"=>array(
        "title"=>"건강기능식품",
        "productInfoProvidedNoticeType" => "DIET_FOOD",
        "article"=>array(
            "product_name"=>array("제품명", ""),
            "food_type"=>array("식품의 유형", ""),
            "producer"=>array("제조업소의 명칭", "수입품의 경우 수입업소명,제조업소명"),
            "location"=>array("제조업소의 소재지", "수입품의 경우 수출국명"),
            "manufacturing_ymd"=>array("제조연월일", ""),
            "expiration_date"=>array("유통기한", ""),
            "waight"=>array("포장단위별 내용물의 용량(중량),수량", ""),
            "quantity"=>array("포장단위별 수량", ""),
            "ingredients"=>array("원재료명 및 함량", "농수산물의 원산지 표시에 관한 법률에 따른 원산지 표시 포함"),
            "nutrition"=>array("영양정보", ""),
            "specification"=>array("기능정보", ""),
            "intake"=>array("섭취량, 섭취방법 및 섭취 시 주의사항 및 부작용 가능성", ""),
            "disease"=>array("질병의 예방 및 치료를 위한 의약품이 아니라는 내용의 표현", ""),
            "genetically_modified"=>array("유전자변형건강기능식품에 해당하는 경우의 표시", ""),
            "imported_food"=>array("수입식품에 해당하는 경우 \"수입식품안전관리특별법에 따른 수입신고를 필함\"의 문구", ""),
            "caution"=>array("소비자안전을 위한 주의사항", ""),
            "as"=>array("소비자상담 관련 전화번호", ""),
        )
    ),
    "kids"=>array(
        "title"=>"영유아용품",
        "productInfoProvidedNoticeType" => "KIDS",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "certification"=>array("KC 인증 필 유무", "어린이제품 안전 특별법 상 안전인증대상어린이제품, 안전확인대상어린이제품, 공급자적합성확인대상어린이제품"),
            "size"=>array("크기", ""),
            "weight"=>array("중량", ""),
            "color"=>array("색상", ""),
            "material"=>array("재질", "섬유의 경우 혼용률"),
            "age"=>array("사용연령 또는 체중범위", "어린이제품 안전 특별법에 따라 표시해야 하는 사항은 반드시 표기"),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "caution"=>array("취급방법 및 취급시 주의사항, 안전표시 (주의, 경고 등)", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "instrument"=>array(
        "title"=>"악기",
        "productInfoProvidedNoticeType" => "MUSICAL_INSTRUMENT",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "size"=>array("크기", ""),
            "color"=>array("색상", ""),
            "material"=>array("재질", ""),
            "components"=>array("제품 구성", ""),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "detailed_specifications"=>array("상품별 세부 사양", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "sports"=>array(
        "title"=>"스포츠용품",
        "productInfoProvidedNoticeType" => "SPORTS_EQUIPMENT",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "size"=>array("크기", ""),
            "weight"=>array("중량", ""),
            "color"=>array("색상", ""),
            "material"=>array("재질", ""),
            "components"=>array("제품구성", ""),
            "released_date"=>array("동일모델의 출시년월", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "detailed_specifications"=>array("상품별 세부 사양", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
        )
    ),
    "books"=>array(
        "title"=>"서적",
        "productInfoProvidedNoticeType" => "BOOKS",
        "article"=>array(
            "product_name"=>array("도서명", ""),
            "author"=>array("저자", ""),
            "publisher"=>array("출판사", ""),
            "size"=>array("크기", "전자책의 경우 파일의 용량"),
            "pages"=>array("쪽수", "전자책의 경우 제외"),
            "components"=>array("제품구성", "전집 또는 세트일 경우 낱권 구성, CD 등"),
            "publish_date"=>array("출간일", ""),
            "description"=>array("목차 또는 책소개", "아동용 학습교재의 경우 사용연령을 포함"),
        )
    ),
    "reserve"=>array(
        "title"=>"호텔/펜션예약",
        "productInfoProvidedNoticeType" => "LODGMENT_RESERVATION",
        "article"=>array(
            "location"=>array("국가 또는 지역명", ""),
            "lodgment_type"=>array("숙소형태", ""),
            "grade"=>array("등급", ""),
            "room_type"=>array("객실타입", ""),
            "room_capacity"=>array("사용가능인원", ""),
            "extra_person_charge"=>array("인원 추가시 비용", ""),
            "facilities"=>array("부대시설", ""),
            "provided_service"=>array("제공서비스", "조식 등"),
            "cancellation_policy"=>array("취소규정", "환불 위약금 등"),
            "booking_contacts"=>array("예약담당 연락처", ""),
        )
    ),
    "travel"=>array(
        "title"=>"여행패키지",
        "productInfoProvidedNoticeType" => "TRAVEL_PACKAGE",
        "article"=>array(
            "travel_agency"=>array("여행사", ""),
            "flight"=>array("이용항공편", ""),
            "travel_period"=>array("여행기간", ""),
            "schedule"=>array("일정", ""),
            "maximum_people"=>array("총예정인원", ""),
            "minimum_people"=>array("출발가능인원", ""),
            "accomodation_info"=>array("숙박정보", ""),
            // "details"=>array("포함내역", "식사, 인솔자, 공연관람 등"),
            // "additional_charge"=>array("추가 경비 항목과 금액", "유류할증료, 공항이용료, 관광지 입장료, 안내원수수료, 식사비용, 선택사항 등"),
            "charge" => array("여행상품 가격", "유류할증료, 공항이용료, 전쟁보험료, 관광진흥개발기금, 운송요금, 숙박요금, 식사요금, 가이드 경비, 여행자보험료, 현지관광입장료 등 소비자가 특정 여행상품을 선택할 경우 부담해야 하는 모든 경비가 포함되어야 함. 다만, 가이드 경비를 현지에서 지불하여야하는 경우 별도로 그 금액을 표시할 수 있으며, 현지에서 별도로 지불해야 한다는 점을 표시하여야 함"),
            "option_charge" => array("선택경비 유무 등", "선택관광 경비 등 현지에서 개별 구매자의 필요나 선택에 의하여 지출하게 되는 경비가 있는 여부 및 소비자의 선택에 따라 자유롭게 지불할 수 있다는 점을 함께 표시하여아 함"),
            "option_schedule" => array("선택관광 및 대체일정", "선택관광 경비의 금액 및 선택관광을 선택하지 않을 경우의 대체 일정을 함께 표시하여야 함"),
            "guide_tip" => array("가이드 팁", "가이드 팁에 대하여 기재할 경우에는 가이드 경비와 구별하여 자유롭게 지불여부를 결정할 수 있음을 표시하여야 함. 다만, 정액으로 지불을 권장하는 등 소비자가 필수적으로 지불하여야 하는 경비인 것처럼 오인하지 않도록 표시하여야 함"),
            "cancellation_policy"=>array("취소규정", "환불, 위약금 등"),
            "travel_warnings"=>array("해외여행의 경우 외교통상부가 지정하는 여행경보단계", ""),
            "booking_contacts"=>array("예약담당 연락처", ""),
        )
    ),
    "airline_ticket"=>array(
        "title"=>"항공권",
        "productInfoProvidedNoticeType" => "AIRLINE_TICKET",
        "article"=>array(
            "charge_condition"=>array("요금조건", ""),
            "round_trip"=>array("왕복&middot;편도 여부", ""),
            "expiration_date"=>array("유효기간", ""),
            "restriction"=>array("제한사항", "출발일, 귀국일 변경가능 여부 등"),
            "ticket_delivery_mean"=>array("티켓수령방법", ""),
            "seat_type"=>array("좌석종류", ""),
            "additional_charge"=>array("가격에 포함되지 않은 내역 및 금액", "유류할증료, 공항이용료 등"),
            "cancellation_policy"=>array("취소 규정", "환불, 위약금 등"),
            "booking_contacts"=>array("예약담당 연락처", ""),
        )
    ),
    "rent_car"=>array(
        "title"=>"자동차대여서비스(렌터카)",
        "productInfoProvidedNoticeType" => "RENT_CAR",
        "article"=>array(
            "model"=>array("차종", ""),
            "ownership_transfer"=>array("소유권 이전 조건", "소유권이 이전되는 경우에 한함"),
            "additional_charge"=>array("추가 선택 시 비용", "자차면책제도, 내비게이션 등"),
            "fuel_cost"=>array("차량 반환 시 연료대금 정산 방법", ""),
            "vehicle_breakdown"=>array("차량의 고장&middot훼손 시 소비자 책임", ""),
            "cancellation_policy"=>array("예약취소 또는 중도 해약 시 환불 기준", ""),
            "as"=>array("소비자상담 관련 전화번호", ""),
        )
    ),
    "rental_water"=>array(
        "title"=>"물품대여서비스(정수기,비데,공기청정기 등)",
        "productInfoProvidedNoticeType" => "RENTAL_HA",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "transfer_of_ownership"=>array("소유권 이전 조건", "소유권이 이전되는 경우에 한하여, 소유권 이전에 필요한 렌탈기간 또는 총 렌탈금액 등 요건을 구체적으로 명시"),
            "maintenance"=>array("유지보수 조건", "점검&middot;필터교환 주기, 추가 비용 등"),
            "consumer_responsibility"=>array("상품의 고장&middot;분실&middot;훼손 시 소비자 책임", ""),
            "refund"=>array("중도 해약 시 환불 기준", ""),
            "specification"=>array("제품 사양", "용량, 소비전력 등"),
            "as"=>array("소비자상담 관련 전화번호", ""),
        )
    ),
    "rental_etc"=>array(
        "title"=>"물품대여서비스(서적,유아용품,행사용품 등)",
        "productInfoProvidedNoticeType" => "RENTAL_ETC",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "transfer_of_ownership"=>array("소유권 이전 조건", "소유권이 이전되는 경우에 한하여, 소유권 이전에 필요한 렌탈기간 또는 총 렌탈금액 등 요건을 구체적으로 명시"),
            "consumer_responsibility"=>array("상품의 고장&middot;분실&middot;훼손 시 소비자 책임", ""),
            "refund"=>array("중도 해약 시 환불 기준", ""),
            "as"=>array("소비자상담 관련 전화번호", ""),
        )
    ),
    "digital_contents"=>array(
        "title"=>"디지털콘텐츠(음원,게임,인터넷강의 등)",
        "productInfoProvidedNoticeType" => "DIGITAL_CONTENTS",
        "article"=>array(
            "producer"=>array("제작자 또는 공급자", ""),
            "terms_of_use"=>array("이용조건", ""),
            "use_period"=>array("이용기간", ""),
            "product_offers"=>array("상품 제공 방식", "CD, 다운로드, 실시간 스트리밍 등"),
            "minimum_system"=>array("최소 시스템 사양, 필수 소프트웨어", ""),
            "maintenance"=>array("청약철회 또는 계약의 해제&middot;해지에 따른 효과", ""),
            "as"=>array("소비자상담 관련 전화번호", "")
        )
    ),
    "gift_card"=>array(
        "title"=>"상품권/쿠폰",
        "productInfoProvidedNoticeType" => "GIFT_CARD",
        "article"=>array(
            "isseur"=>array("발행자", ""),
            "expiration_date"=>array("유효기간", "유효기간 경과 시 보상 기준"),
            "terms_of_use"=>array("이용조건", "사용제한품목 및 기간 등"),
            "use_store"=>array("이용 가능 매장", ""),
            "refund_policy"=>array("잔액 환급 조건", ""),
            "as"=>array("소비자상담 관련 전화번호", "")
        )
    ),
    "mobile_coupon" => array(
        "title" => "모바일쿠폰",
        "productInfoProvidedNoticeType" => "MOBILE_COUPON",
        "article" => array(
            "isseur" => array("발행자", ""),
            "expiration_date" => array("유효기간", "유효기간 경과시 보상 기준 포함"),
            "use_store" => array("이용 가능 매장", ""),
            "refund_policy" => array("환불조건 및 방법", ""),
            "as" => array("소비자상담 관련 전화번호", "")
        )
    ),
    "movie_show" => array(
        "title" => "영화&middot공연",
        "productInfoProvidedNoticeType" => "MOVIE_SHOW",
        "article"           => array(
            "sponsor"       => array("주최 또는 기획", "공연에 한함"),
            "actor"         => array("주연", "공연에 한함"),
            "rating"        => array("관람등급", ""),
            "showTime"      => array("상영&middot공연시간", ""),
            "showPlace"     => array("상영&middot공연장소", ""),
            "cancelationCondition"   => array("예매 취소 조건", ""),
            "cancelationPolicy" => array("취소&middot환불방법", ""),
            "customerServicePhoneNumber" => array("소비자상담 관련 전화번호", "")
        )
    ),
    "biochemistry" => array(
        "title" => "생활화학제품",
        "productInfoProvidedNoticeType" => "BIOCHEMISTRY",
        "article" => array(
            "productName"           => array("품목 및 제품명", ""),
            "dosageForm"            => array("용도 및 제형", "표백제의 경우 계열을 함께 표시"),
            "packDateText"          => array("제조연월", ""),
            "expirationDateText"    => array("유통기한", "해당 없는 제품 생략 가능"),
            "weight"                => array("중량&middot용량&middot매수", ""),
            "effect"                => array("효과&middot효능", "승인대상 제품에 한함"),
            "importer"              => array("수입자", "수입제품에 한함"),
            "producer"              => array("제조국", ""),
            "manufacturer"          => array("제조사", ""),
            "childProtection"       => array("어린이 보호포장 대상 제품 유무", ""),
            "chemicals"             => array("제품에 사용된 화학물질 명칭", "주요물질,보존제 등 관련 고시에 따른 표시의무 화학물질에 한함"),
            "caution"               => array("사용상 주의사항", ""),
            "safeCriterionNo"       => array("안전기준 적합확인 신고번호(자가검사번호)또는 안전확인대상 생활화학제품 승인번호", ""),
            "customerServicePhoneNumber" => array("소비자상담 관련 전화번호", "")
        )
    ),
    "biocidal" => array(
        "title" => "살생물제품",
        "productInfoProvidedNoticeType" => "BIOCIDAL",
        "article" => array(
            "product_name"      => array("제품명 및 제품유형", ""),
            "weight"            => array("중량 또는 용량 및 표준사용량", ""),
            "effect"            => array("효과&middot효능", ""),
            "rangeOfUse"        => array("사용대상자 및 사용범위", ""),
            "importer"          => array("수입자", "수입제품에 한함"),
            "producer"          => array("제조국", ""),
            "manufacturer"      => array("제조사", ""),
            "child_protection"  => array("어린이 보호포장 대상 제품 유무", ""),
            "harmfulChemicalSubstance" => array("살생물물질,나노물질,기타 화학물질(유해화학물질 또는 중점관리물질)의 명칭", ""),
            "maleficence"       => array("제품 유해성&middot위해성 표시", ""),
            "caution"           => array("사용방법 및 사용상 주의사항", ""),
            "approvalNumber"    => array("승인번호", ""),
            "as"                => array("소비자상담 관련 전화번호", "")
        )
    ),
    "etcService" => array(
        "title" => "기타 용역",
        "productInfoProvidedNoticeType" => "ETC_SERVICE",
        "article" => array(
            "serviceProvider"   => array("서비스 제공 사업자", ""),
            "certificateDetails"       => array("법에 의한 인증&middot허가 등을 받았음을 확인할 수 있는 경우 그에 대한 사항", ""),
            "usableCondition"         => array("이용조건", "이용가능 기간&middot장소, 추가비용 등"),
            "cancelationStandard"   => array("취소&middot중도해약&middot해지 조건 및 환불기준", ""),
            "cancelationPolicy"     => array("취소&middot환불방법", ""),
            "customerServicePhoneNumber"                => array("소비자상담 관련 전화번호", "")
        )
    ),
    "etc"=>array(
        "title"=>"기타",
        "productInfoProvidedNoticeType" => "ETC",
        "article"=>array(
            "product_name"=>array("품명", ""),
            "model_name"=>array("모델명", ""),
            "certified_by_law"=>array("법에 의한 인증&middot허가 등을 받았음을 확인할 수 있는 경우 그에 대한 사항", ""),
            "origin"=>array("제조국 또는 원산지", ""),
            "maker"=>array("제조자", "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "as"=>array("A/S 책임자와 전화번호 또는 소비자상담 관련 전화번호", "")
        )
    ),
);